### ISSUE TITLE
Can't checkout your project on Mac file systems

### ISSUE THREAD

**Issue by mfrohike** [belen-albeza/obsidian-starter-vault#1]
Hi! Thank you for your great work with this repo.

I have tried  to clone the repo  on a Mac Catalina. Cloning succeeded but  checkout failed with "Illegal byte sequence" error. I think it is due to a macOs limitation with file names: https://stackoverflow.com/questions/57732278/git-checkout-failed-with-illegal-byte-sequence.

`Cloning into 'obsidian-starter-vault'...
remote: Enumerating objects: 110, done.
remote: Total 110 (delta 0), reused 0 (delta 0), pack-reused 110
Receiving objects: 100% (110/110), 1.86 MiB | 5.61 MiB/s, done.
Resolving deltas: 100% (18/18), done.
error: unable to create file vault/⚙️ Meta/🪴 Tending this Garden.md: Illegal byte sequence
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'`

Is there any alternative that works with Mac's ?

Thanks

**Comment by belen-albeza** [comment]
I think the issue is that older versions of the OS don't support some of the newer emojis. Updating the OS should work (I use a Mac), but I'll look into maybe picking older ones for filenames.
